package com.example.util

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.getValue
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
  TR("tr", "Türkçe", "🇹🇷"),
  EN("en", "English", "🇬🇧"),
  ES("es", "Español", "🇪🇸"),
  DE("de", "Deutsch", "🇩🇪");

  companion object {
    fun fromCode(code: String): AppLanguage {
      return values().find { it.code.equals(code, ignoreCase = true) } ?: TR
    }
  }
}

object LocalizationManager {
  private const val PREFS_NAME = "language_prefs"
  private const val KEY_LANG = "selected_lang"

  private val _currentLanguage = MutableStateFlow(AppLanguage.TR)
  val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

  fun init(context: Context) {
    val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    val saved = prefs.getString(KEY_LANG, AppLanguage.TR.code) ?: AppLanguage.TR.code
    _currentLanguage.value = AppLanguage.fromCode(saved)
  }

  fun setLanguage(context: Context, lang: AppLanguage) {
    _currentLanguage.value = lang
    val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    prefs.edit().putString(KEY_LANG, lang.code).apply()
  }

  fun string(key: String): String {
    val lang = _currentLanguage.value
    return TRANSLATIONS[lang]?.get(key)
      ?: TRANSLATIONS[AppLanguage.EN]?.get(key)
      ?: TRANSLATIONS[AppLanguage.TR]?.get(key)
      ?: key
  }

  fun string(key: String, vararg args: Any): String {
    val template = string(key)
    return try {
      String.format(template, *args)
    } catch (e: Exception) {
      template
    }
  }

  private val TRANSLATIONS: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.TR to mapOf(
      "app_name" to "Time Rush",
      // Navigation
      "home" to "Ana Sayfa",
      "games" to "Oyunlar",
      "leaderboard" to "Liderlik",
      "profile" to "Profil",
      "settings" to "Ayarlar",
      "sound_fx" to "Ses Efektleri",
      "haptic_vibration" to "Haptik Titreşim",
      "language" to "Uygulama Dili",
      "privacy_policy" to "Gizlilik Politikası",
      "tab_world" to "🌍 Dünya",
      "tab_turkey" to "🇹🇷 Türkiye",
      "cloud_live" to "Canlı Bulut Sıralaması",
      "local_mode" to "Yerel Mod (Giriş Yapılmadı)",
      "edit_profile" to "Profili Düzenle",
      "change_nickname" to "Takma İsim Değiştir",
      "nickname_label" to "Oyuncu Adı (Takma İsim)",
      "city_country" to "Şehir / Bölge",
      "save_update" to "Kaydet & Güncelle",
      "cancel" to "İptal",
      "sign_in_google" to "Google ile Giriş Yap",
      "sign_out" to "Çıkış Yap",
      "save_score_cloud" to "Skoru Kaydet",
      "quick_play" to "HIZLI OYNA",
      "start_game" to "BAŞLAT",
      "time_up" to "Süre doldu!",
      "play_again" to "Tekrar Oyna",
      "continue_game" to "Devam Et",
      "watch_ad_double" to "2X Skor & XP (Reklam)",
      "revive_title" to "OYUNA DEVAM ET?",
      "revive_desc" to "Reklam izleyerek +5 saniye ile devam edebilirsin.",
      "revive_btn" to "Reklam İzle & Devam Et (+5s)",
      "skip_and_finish" to "Hayır, Oyunu Bitir",
      "lucky_wheel" to "Şans Çarkı",
      "daily_missions" to "Günlük Görevler",
      "store_avatars" to "Karakter Dükkanı",
      "profanity_error" to "Lütfen topluluk kurallarına uygun, saygılı bir takma isim seçin.",
      "name_too_short" to "İsim en az 2 karakter olmalıdır.",
      "name_too_long" to "İsim en fazla 16 karakter olabilir.",
      "top_brains" to "👑 ZİRVEDEKİ OYUNCULAR",
      "level_label" to "Seviye",
      "streak_label" to "Seri",
      "coins_label" to "Altın",
      "score_label" to "Skorun",
      "xp_gained" to "XP Kazanımı",
      "brain_score" to "Beyin Puanı",
      "claim_reward" to "ÖDÜLÜ AL",
      "claimed" to "Alındı ✓",
      "daily_wheel_title" to "🎯 Günlük Çark",
      "daily_wheel_ready" to "Hediye altın & XP seni bekliyor!",
      "daily_wheel_done" to "Bugün çevrildi (Reklamla +1)",
      "spin_now" to "ŞİMDİ ÇEVİR ➔",
      "details" to "DETAY ➔",
      "reaction_speed_title" to "⚡ Tepki Hızın",
      "reaction_analysis_btn" to "ANALİZİ GÖR ➔",
      "quick_play_title" to "Hızlı Oyun Modu",
      "quick_play_sub" to "10 saniyede refleksini test et!",
      "play_btn" to "OYNA ⚡",
      "cat_reflex" to "Refleks",
      "cat_logic" to "Mantık",
      "cat_memory" to "Hafıza",
      "cat_attention" to "Dikkat",
      "ranking_btn" to "SIRALAMA ➔",
      "games_title" to "🎮 Mini Oyunlar",
      "games_subtitle" to "Refleks, zeka, hafıza ve odaklanma antrenmanı",
      "all_filter" to "Tümü",
      "play_game_btn" to "OYUNA BAŞLA",
      "start_sub1" to "10 saniyede ne kadar iyisin?",
      "start_sub2" to "Refleks • Zeka • Dikkat • Hafıza",
      "start_privacy" to "🔒 Gizlilik Politikası & Play Store Beyanı",
      "leagues" to "Ligler",
      "game_won_title" to "Harika!",
      "game_lost_title" to "Süre Doldu!",
      "game_won_desc" to "Bu turu başarıyla kazandın!",
      "risk_mode_reward_active" to "🔥 3X RİSK ÖDÜLÜ AKTİF EDİLDİ!",
      "watch_ad_2x" to "Reklam İzle & 2X Skor Kazan!",
      "watch_ad_2x_sub" to "+%d Ek Puan & +50 Altın",
      "watch_ad_second_chance" to "Reklam İzle & İkinci Şans (+5s) Al!",
      "safe_mode" to "Güvenli Mod",
      "risk_mode" to "Risk Modu (3X Skor & XP)",
      "safe_mode_desc" to "Standart süre, hata yapsan da devam et",
      "risk_mode_desc" to "Yarı süre, 0 hata toleransı, 3 kat ödül!",
      "start_safe" to "GÜVENLİ BAŞLA",
      "start_risk" to "RİSK AL & 3X KAZAN 🔥",
      // Mini Games in-game
      "rule_prefix" to "KURAL:",
      "rule_stroop_word" to "YAZILAN KELİMENİN RENGİNE BAS!",
      "rule_stroop_ink" to "MÜREKKEP / YAZI RENGİNE BAS!",
      "stroop_tap_balloon" to "👇 AŞAĞIDAKİ DOĞRU BALONA DOKUN 👇",
      "color_red" to "Kırmızı",
      "color_blue" to "Mavi",
      "color_green" to "Yeşil",
      "color_yellow" to "Sarı",
      "color_purple" to "Mor",
      "tap_green" to "🟢 YEŞİLE BAS!",
      "avoid_red" to "🔴 KIRMIZIDAN KAÇIN!",
      "round_label" to "Tur",
      "correct_feedback" to "✓ DOĞRU!",
      "wrong_feedback" to "✗ YANLIŞ!",
      "inspect_symbols" to "👁️ 2 SANİYE İNCELE!",
      "tap_changed_symbol" to "👇 DEĞİŞEN YENİ SEMBOLE DOKUN! 👇",
      "press_stop" to "DURDUR",
      "stopped" to "DURDURULDU",
      "target_label" to "HEDEF:",
      "current_label" to "ŞU AN:",
      "precision_stop" to "🎯 HAREKETLİ ÇUBUĞU HEDEFTE DURDUR!",
      "type_answer" to "Cevabı Yaz...",
      "check_btn" to "KONTROL ET",
      "next_number_pattern" to "Sıradaki sayıyı mantıksal kurala göre bul:",
      "remember_sequence" to "Rakamları aklında tut ve sırayla gir:",
      "find_diff_instruction" to "🔍 ALTTTAKİ RESİMDEKİ FARKA DOKUN! 🔍"
    ),

    AppLanguage.EN to mapOf(
      "app_name" to "Time Rush",
      // Navigation
      "home" to "Home",
      "games" to "Games",
      "leaderboard" to "Leaderboard",
      "profile" to "Profile",
      "settings" to "Settings",
      "sound_fx" to "Sound Effects",
      "haptic_vibration" to "Haptic Feedback",
      "language" to "Language",
      "privacy_policy" to "Privacy Policy",
      "tab_world" to "🌍 World",
      "tab_turkey" to "🇹🇷 Turkey",
      "cloud_live" to "Live Cloud Ranking",
      "local_mode" to "Local Mode (Not Signed In)",
      "edit_profile" to "Edit Profile",
      "change_nickname" to "Change Nickname",
      "nickname_label" to "Player Nickname",
      "city_country" to "City / Region",
      "save_update" to "Save & Update",
      "cancel" to "Cancel",
      "sign_in_google" to "Sign In with Google",
      "sign_out" to "Sign Out",
      "save_score_cloud" to "Save Score",
      "quick_play" to "QUICK PLAY",
      "start_game" to "START",
      "time_up" to "Time's up!",
      "play_again" to "Play Again",
      "continue_game" to "Continue",
      "watch_ad_double" to "2X Score & XP (Watch Ad)",
      "revive_title" to "KEEP PLAYING?",
      "revive_desc" to "Watch a short ad to resume with +5 extra seconds.",
      "revive_btn" to "Watch Ad & Continue (+5s)",
      "skip_and_finish" to "No, Finish Game",
      "lucky_wheel" to "Lucky Wheel",
      "daily_missions" to "Daily Missions",
      "store_avatars" to "Avatar Shop",
      "profanity_error" to "Please choose an appropriate and respectful nickname.",
      "name_too_short" to "Name must be at least 2 characters.",
      "name_too_long" to "Name must be at most 16 characters.",
      "top_brains" to "👑 TOP LEADERBOARD",
      "level_label" to "Level",
      "streak_label" to "Streak",
      "coins_label" to "Coins",
      "score_label" to "Your Score",
      "xp_gained" to "XP Earned",
      "brain_score" to "Brain Score",
      "claim_reward" to "CLAIM REWARD",
      "claimed" to "Claimed ✓",
      "daily_wheel_title" to "🎯 Daily Wheel",
      "daily_wheel_ready" to "Free coins & XP await you!",
      "daily_wheel_done" to "Claimed today (Watch ad for +1)",
      "spin_now" to "SPIN NOW ➔",
      "details" to "DETAILS ➔",
      "reaction_speed_title" to "⚡ Reaction Speed",
      "reaction_analysis_btn" to "VIEW STATS ➔",
      "quick_play_title" to "Quick Play Mode",
      "quick_play_sub" to "Test your reflexes in 10 seconds!",
      "play_btn" to "PLAY ⚡",
      "cat_reflex" to "Reflex",
      "cat_logic" to "Logic",
      "cat_memory" to "Memory",
      "cat_attention" to "Focus",
      "ranking_btn" to "RANKINGS ➔",
      "games_title" to "🎮 Mini Games",
      "games_subtitle" to "Reflex, IQ, memory & concentration trainer",
      "all_filter" to "All",
      "play_game_btn" to "START GAME",
      "start_sub1" to "How fast are your brains in 10s?",
      "start_sub2" to "Reflex • Logic • Attention • Memory",
      "start_privacy" to "🔒 Privacy Policy & Play Store Statement",
      "leagues" to "Leagues",
      "game_won_title" to "Awesome!",
      "game_lost_title" to "Time's Up!",
      "game_won_desc" to "You successfully won this round!",
      "risk_mode_reward_active" to "🔥 3X RISK REWARD ACTIVATED!",
      "watch_ad_2x" to "Watch Ad & Double Score!",
      "watch_ad_2x_sub" to "+%d Extra Points & +50 Coins",
      "watch_ad_second_chance" to "Watch Ad & Get Second Chance (+5s)!",
      "safe_mode" to "Safe Mode",
      "risk_mode" to "Risk Mode (3X Score & XP)",
      "safe_mode_desc" to "Standard time, mistakes don't end the run",
      "risk_mode_desc" to "Half time, 0 mistake tolerance, 3x reward!",
      "start_safe" to "START SAFE",
      "start_risk" to "RISK & WIN 3X 🔥",
      // Mini Games in-game
      "rule_prefix" to "RULE:",
      "rule_stroop_word" to "TAP THE COLOR OF THE TEXT WORD!",
      "rule_stroop_ink" to "TAP THE INK / DISPLAY COLOR!",
      "stroop_tap_balloon" to "👇 TAP THE CORRECT BALLOON BELOW 👇",
      "color_red" to "Red",
      "color_blue" to "Blue",
      "color_green" to "Green",
      "color_yellow" to "Yellow",
      "color_purple" to "Purple",
      "tap_green" to "🟢 TAP GREEN!",
      "avoid_red" to "🔴 AVOID RED!",
      "round_label" to "Round",
      "correct_feedback" to "✓ CORRECT!",
      "wrong_feedback" to "✗ WRONG!",
      "inspect_symbols" to "👁️ MEMORIZE FOR 2 SECONDS!",
      "tap_changed_symbol" to "👇 TAP THE NEW CHANGED SYMBOL! 👇",
      "press_stop" to "STOP",
      "stopped" to "STOPPED",
      "target_label" to "TARGET:",
      "current_label" to "CURRENT:",
      "precision_stop" to "🎯 STOP THE BAR EXACTLY ON TARGET!",
      "type_answer" to "Type answer...",
      "check_btn" to "CHECK",
      "next_number_pattern" to "Find the next number in the pattern:",
      "remember_sequence" to "Memorize the sequence and tap in order:",
      "find_diff_instruction" to "🔍 TAP THE DIFFERENCE ON BOTTOM IMAGE! 🔍"
    ),

    AppLanguage.ES to mapOf(
      "app_name" to "Time Rush",
      // Navigation
      "home" to "Inicio",
      "games" to "Juegos",
      "leaderboard" to "Clasificación",
      "profile" to "Perfil",
      "settings" to "Ajustes",
      "sound_fx" to "Efectos de Sonido",
      "haptic_vibration" to "Vibración Háptica",
      "language" to "Idioma",
      "privacy_policy" to "Política de Privacidad",
      "tab_world" to "🌍 Mundial",
      "tab_turkey" to "🇹🇷 Turquía",
      "cloud_live" to "Clasificación en Nube",
      "local_mode" to "Modo Local (Sin Conexión)",
      "edit_profile" to "Editar Perfil",
      "change_nickname" to "Cambiar Apodo",
      "nickname_label" to "Apodo del Jugador",
      "city_country" to "Ciudad / Región",
      "save_update" to "Guardar y Actualizar",
      "cancel" to "Cancelar",
      "sign_in_google" to "Iniciar con Google",
      "sign_out" to "Cerrar Sesión",
      "save_score_cloud" to "Guardar Puntuación",
      "quick_play" to "PARTIDA RÁPIDA",
      "start_game" to "EMPEZAR",
      "time_up" to "¡Tiempo terminado!",
      "play_again" to "Jugar de Nuevo",
      "continue_game" to "Continuar",
      "watch_ad_double" to "2X Puntos y XP (Ver Anuncio)",
      "revive_title" to "¿SEGUIR JUGANDO?",
      "revive_desc" to "Mira un anuncio para continuar con +5 segundos extras.",
      "revive_btn" to "Ver Anuncio y Seguir (+5s)",
      "skip_and_finish" to "No, Terminar Partida",
      "lucky_wheel" to "Ruleta de la Suerte",
      "daily_missions" to "Misiones Diarias",
      "store_avatars" to "Tienda de Avatares",
      "profanity_error" to "Por favor elige un apodo respetuoso.",
      "name_too_short" to "El nombre debe tener al menos 2 caracteres.",
      "name_too_long" to "El nombre no puede superar 16 caracteres.",
      "top_brains" to "👑 MEJORES JUGADORES",
      "level_label" to "Nivel",
      "streak_label" to "Racha",
      "coins_label" to "Monedas",
      "score_label" to "Tu Puntuación",
      "xp_gained" to "XP Ganada",
      "brain_score" to "Puntos Cerebrales",
      "claim_reward" to "RECLAMAR RECOMPENSA",
      "claimed" to "Reclamado ✓",
      "daily_wheel_title" to "🎯 Ruleta Diaria",
      "daily_wheel_ready" to "¡Monedas y XP gratis te esperan!",
      "daily_wheel_done" to "Reclamado hoy (+1 con anuncio)",
      "spin_now" to "GIRAR AHORA ➔",
      "details" to "DETALLES ➔",
      "reaction_speed_title" to "⚡ Velocidad de Reacción",
      "reaction_analysis_btn" to "VER ANÁLISIS ➔",
      "quick_play_title" to "Modo Rápido",
      "quick_play_sub" to "¡Pon a prueba tus reflejos en 10s!",
      "play_btn" to "JUGAR ⚡",
      "cat_reflex" to "Reflejos",
      "cat_logic" to "Lógica",
      "cat_memory" to "Memoria",
      "cat_attention" to "Atención",
      "ranking_btn" to "CLASIFICACIÓN ➔",
      "games_title" to "🎮 Mini Juegos",
      "games_subtitle" to "Entrenamiento de reflejos, mente y memoria",
      "all_filter" to "Todos",
      "play_game_btn" to "JUGAR AHORA",
      "start_sub1" to "¿Qué tan rápido eres en 10 segundos?",
      "start_sub2" to "Reflejos • Lógica • Atención • Memoria",
      "start_privacy" to "🔒 Política de Privacidad & Google Play",
      "leagues" to "Ligas",
      "game_won_title" to "¡Excelente!",
      "game_lost_title" to "¡Tiempo Agotado!",
      "game_won_desc" to "¡Has ganado esta ronda con éxito!",
      "risk_mode_reward_active" to "🔥 ¡RECOMPENSA DE RIESGO 3X ACTIVADA!",
      "watch_ad_2x" to "Ver Anuncio y Duplicar Puntos",
      "watch_ad_2x_sub" to "+%d Puntos Extra y +50 Monedas",
      "watch_ad_second_chance" to "Ver Anuncio y Segunda Oportunidad (+5s)",
      "safe_mode" to "Modo Seguro",
      "risk_mode" to "Modo Riesgo (3X Puntos & XP)",
      "safe_mode_desc" to "Tiempo estándar, los errores no terminan el juego",
      "risk_mode_desc" to "Mitad de tiempo, 0 errores tolerados, 3x recompensa",
      "start_safe" to "INICIAR SEGURO",
      "start_risk" to "ARRIESGAR Y GANAR 3X 🔥",
      // Mini Games in-game
      "rule_prefix" to "REGLA:",
      "rule_stroop_word" to "¡PULSA EL COLOR DE LA PALABRA!",
      "rule_stroop_ink" to "¡PULSA EL COLOR DE LA TINTA / TEXTO!",
      "stroop_tap_balloon" to "👇 TOCA EL GLOBO CORRECTO ABAJO 👇",
      "color_red" to "Rojo",
      "color_blue" to "Azul",
      "color_green" to "Verde",
      "color_yellow" to "Amarillo",
      "color_purple" to "Morado",
      "tap_green" to "🟢 ¡PULSA VERDE!",
      "avoid_red" to "🔴 ¡EVITA ROJO!",
      "round_label" to "Ronda",
      "correct_feedback" to "✓ ¡CORRECTO!",
      "wrong_feedback" to "✗ ¡INCORRECTO!",
      "inspect_symbols" to "👁️ ¡MEMORIZA POR 2 SEGUNDOS!",
      "tap_changed_symbol" to "👇 ¡TOCA EL SÍMBOLO QUE HA CAMBIADO! 👇",
      "press_stop" to "PARAR",
      "stopped" to "DETENIDO",
      "target_label" to "OBJETIVO:",
      "current_label" to "ACTUAL:",
      "precision_stop" to "🎯 ¡DETÉN LA BARRA EXACTAMENTE EN EL OBJETIVO!",
      "type_answer" to "Escribe respuesta...",
      "check_btn" to "COMPROBAR",
      "next_number_pattern" to "Encuentra el siguiente número de la serie:",
      "remember_sequence" to "Recuerda los números e ingrésalos en orden:",
      "find_diff_instruction" to "🔍 ¡TOCA LA DIFERENCIA EN LA IMAGEN INFERIOR! 🔍"
    ),

    AppLanguage.DE to mapOf(
      "app_name" to "Time Rush",
      // Navigation
      "home" to "Start",
      "games" to "Spiele",
      "leaderboard" to "Bestenliste",
      "profile" to "Profil",
      "settings" to "Einstellungen",
      "sound_fx" to "Soundeffekte",
      "haptic_vibration" to "Haptisches Feedback",
      "language" to "Sprache",
      "privacy_policy" to "Datenschutz",
      "tab_world" to "🌍 Weltweit",
      "tab_turkey" to "🇹🇷 Türkei",
      "cloud_live" to "Live Cloud-Rangliste",
      "local_mode" to "Lokaler Modus (Nicht angemeldet)",
      "edit_profile" to "Profil Bearbeiten",
      "change_nickname" to "Spitzname Ändern",
      "nickname_label" to "Spielername",
      "city_country" to "Stadt / Region",
      "save_update" to "Speichern & Aktualisieren",
      "cancel" to "Abbrechen",
      "sign_in_google" to "Mit Google anmelden",
      "sign_out" to "Abmelden",
      "save_score_cloud" to "Punkte Speichern",
      "quick_play" to "SCHNELLSPIEL",
      "start_game" to "STARTEN",
      "time_up" to "Zeit ist um!",
      "play_again" to "Nochmal Spielen",
      "continue_game" to "Weiter",
      "watch_ad_double" to "2X Punkte & XP (Werbung)",
      "revive_title" to "WEITERSPIELEN?",
      "revive_desc" to "Kurzes Video ansehen für +5 Sekunden extra.",
      "revive_btn" to "Werbung sehen & weiter (+5s)",
      "skip_and_finish" to "Nein, Spiel beenden",
      "lucky_wheel" to "Glücksrad",
      "daily_missions" to "Tägliche Missionen",
      "store_avatars" to "Avatar-Shop",
      "profanity_error" to "Bitte wähle einen angemessenen Spitznamen.",
      "name_too_short" to "Name muss mindestens 2 Zeichen haben.",
      "name_too_long" to "Name darf maximal 16 Zeichen haben.",
      "top_brains" to "👑 BESTE SPIELER",
      "level_label" to "Level",
      "streak_label" to "Serie",
      "coins_label" to "Münzen",
      "score_label" to "Deine Punkte",
      "xp_gained" to "XP Verdient",
      "brain_score" to "Gehirn-Punkte",
      "claim_reward" to "BELOHNUNG HOLEN",
      "claimed" to "Erhalten ✓",
      "daily_wheel_title" to "🎯 Glücksrad",
      "daily_wheel_ready" to "Kostenlose Münzen & XP warten auf dich!",
      "daily_wheel_done" to "Heute beansprucht (+1 mit Werbung)",
      "spin_now" to "JETZT DREHEN ➔",
      "details" to "DETAILS ➔",
      "reaction_speed_title" to "⚡ Reaktionszeit",
      "reaction_analysis_btn" to "ANALYSE ANZEIGEN ➔",
      "quick_play_title" to "Schnellspiel-Modus",
      "quick_play_sub" to "Teste deine Reflexe in 10 Sekunden!",
      "play_btn" to "SPIELEN ⚡",
      "cat_reflex" to "Reflexe",
      "cat_logic" to "Logik",
      "cat_memory" to "Gedächtnis",
      "cat_attention" to "Fokus",
      "ranking_btn" to "RANGLISTE ➔",
      "games_title" to "🎮 Minispiele",
      "games_subtitle" to "Reflex-, Denk- und Gedächtnistraining",
      "all_filter" to "Alle",
      "play_game_btn" to "SPIEL STARTEN",
      "start_sub1" to "Wie schnell bist du in 10 Sekunden?",
      "start_sub2" to "Reflexe • Logik • Fokus • Gedächtnis",
      "start_privacy" to "🔒 Datenschutz & Google Play Richtlinie",
      "leagues" to "Ligen",
      "game_won_title" to "Großartig!",
      "game_lost_title" to "Zeit ist um!",
      "game_won_desc" to "Du hast diese Runde erfolgreich gewonnen!",
      "risk_mode_reward_active" to "🔥 3X RISIKO-BELOHNUNG AKTIVIERT!",
      "watch_ad_2x" to "Werbung ansehen & 2X Punkte!",
      "watch_ad_2x_sub" to "+%d Extrapunkte & +50 Münzen",
      "watch_ad_second_chance" to "Werbung ansehen & 2. Chance (+5s)!",
      "safe_mode" to "Sicherer Modus",
      "risk_mode" to "Risikomodus (3X Punkte & XP)",
      "safe_mode_desc" to "Standardzeit, Fehler beenden das Spiel nicht",
      "risk_mode_desc" to "Halbe Zeit, 0 Fehlertoleranz, 3x Belohnung!",
      "start_safe" to "SICHER STARTEN",
      "start_risk" to "RISIKO & 3X GEWINNEN 🔥",
      // Mini Games in-game
      "rule_prefix" to "REGEL:",
      "rule_stroop_word" to "DRÜCKE DIE FARBE DES GESCHRIEBENEN WORTES!",
      "rule_stroop_ink" to "DRÜCKE DIE TEXT-/SCHRIFTFARBE!",
      "stroop_tap_balloon" to "👇 TIPPE AUF DEN RICHTIGEN BALLON UNTEN 👇",
      "color_red" to "Rot",
      "color_blue" to "Blau",
      "color_green" to "Grün",
      "color_yellow" to "Gelb",
      "color_purple" to "Lila",
      "tap_green" to "🟢 GRÜN TIPPEN!",
      "avoid_red" to "🔴 ROT VERMEIDEN!",
      "round_label" to "Runde",
      "correct_feedback" to "✓ RICHTIG!",
      "wrong_feedback" to "✗ FALSCH!",
      "inspect_symbols" to "👁️ 2 SEKUNDEN EINPRÄGEN!",
      "tap_changed_symbol" to "👇 TIPPE AUF DAS GEÄNDERTE SYMBOL! 👇",
      "press_stop" to "STOPP",
      "stopped" to "ANGEHALTEN",
      "target_label" to "ZIEL:",
      "current_label" to "AKTUELL:",
      "precision_stop" to "🎯 STOPPE DEN BALKEN GENAU IM ZIEL!",
      "type_answer" to "Antwort eingeben...",
      "check_btn" to "PRÜFEN",
      "next_number_pattern" to "Finde die nächste Zahl im Muster:",
      "remember_sequence" to "Merke dir die Zahlenfolge und tippe sie ein:",
      "find_diff_instruction" to "🔍 TIPPE AUF DEN UNTERSCHIED IM UNTEREN BILD! 🔍"
    )
  )
}
